language: python
python:
- "3.6"
cache: pip
install:
- wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda create -q -n test-env python=$TRAVIS_PYTHON_VERSION
- source activate test-env
- conda install hyperspy -c conda-forge
- conda install -c pycalphad -c msys2 -c conda-forge pycalphad
- pip install --upgrade pip
- pip install -e .
- pip install -r requirements.txt -U --upgrade-strategy eager
- pip install -r test_requirements.txt
script:
- flake8 . && travis_wait 50 py.test
after_success:
- coveralls
